package com.join.greenDaoUtils;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STORAGE".
*/
public class StorageDao extends AbstractDao<Storage, Long> {

    public static final String TABLENAME = "STORAGE";

    /**
     * Properties of entity Storage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Number = new Property(1, int.class, "number", false, "NUMBER");
        public final static Property Date = new Property(2, String.class, "date", false, "DATE");
        public final static Property Time = new Property(3, String.class, "time", false, "TIME");
        public final static Property Type = new Property(4, String.class, "type", false, "TYPE");
        public final static Property Color = new Property(5, String.class, "color", false, "COLOR");
        public final static Property Smell = new Property(6, String.class, "smell", false, "SMELL");
        public final static Property Density = new Property(7, String.class, "density", false, "DENSITY");
        public final static Property Vitality = new Property(8, String.class, "vitality", false, "VITALITY");
        public final static Property MotilityRate = new Property(9, String.class, "motilityRate", false, "MOTILITY_RATE");
        public final static Property Line = new Property(10, String.class, "line", false, "LINE");
        public final static Property Operator = new Property(11, String.class, "operator", false, "OPERATOR");
        public final static Property Result = new Property(12, String.class, "result", false, "RESULT");
    }


    public StorageDao(DaoConfig config) {
        super(config);
    }
    
    public StorageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STORAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NUMBER\" INTEGER NOT NULL UNIQUE ," + // 1: number
                "\"DATE\" TEXT," + // 2: date
                "\"TIME\" TEXT," + // 3: time
                "\"TYPE\" TEXT," + // 4: type
                "\"COLOR\" TEXT," + // 5: color
                "\"SMELL\" TEXT," + // 6: smell
                "\"DENSITY\" TEXT," + // 7: density
                "\"VITALITY\" TEXT," + // 8: vitality
                "\"MOTILITY_RATE\" TEXT," + // 9: motilityRate
                "\"LINE\" TEXT," + // 10: line
                "\"OPERATOR\" TEXT," + // 11: operator
                "\"RESULT\" TEXT);"); // 12: result
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STORAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Storage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getNumber());
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(3, date);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(4, time);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(5, type);
        }
 
        String color = entity.getColor();
        if (color != null) {
            stmt.bindString(6, color);
        }
 
        String smell = entity.getSmell();
        if (smell != null) {
            stmt.bindString(7, smell);
        }
 
        String density = entity.getDensity();
        if (density != null) {
            stmt.bindString(8, density);
        }
 
        String vitality = entity.getVitality();
        if (vitality != null) {
            stmt.bindString(9, vitality);
        }
 
        String motilityRate = entity.getMotilityRate();
        if (motilityRate != null) {
            stmt.bindString(10, motilityRate);
        }
 
        String line = entity.getLine();
        if (line != null) {
            stmt.bindString(11, line);
        }
 
        String operator = entity.getOperator();
        if (operator != null) {
            stmt.bindString(12, operator);
        }
 
        String result = entity.getResult();
        if (result != null) {
            stmt.bindString(13, result);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Storage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getNumber());
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(3, date);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(4, time);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(5, type);
        }
 
        String color = entity.getColor();
        if (color != null) {
            stmt.bindString(6, color);
        }
 
        String smell = entity.getSmell();
        if (smell != null) {
            stmt.bindString(7, smell);
        }
 
        String density = entity.getDensity();
        if (density != null) {
            stmt.bindString(8, density);
        }
 
        String vitality = entity.getVitality();
        if (vitality != null) {
            stmt.bindString(9, vitality);
        }
 
        String motilityRate = entity.getMotilityRate();
        if (motilityRate != null) {
            stmt.bindString(10, motilityRate);
        }
 
        String line = entity.getLine();
        if (line != null) {
            stmt.bindString(11, line);
        }
 
        String operator = entity.getOperator();
        if (operator != null) {
            stmt.bindString(12, operator);
        }
 
        String result = entity.getResult();
        if (result != null) {
            stmt.bindString(13, result);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Storage readEntity(Cursor cursor, int offset) {
        Storage entity = new Storage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // number
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // date
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // time
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // type
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // color
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // smell
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // density
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // vitality
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // motilityRate
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // line
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // operator
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // result
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Storage entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNumber(cursor.getInt(offset + 1));
        entity.setDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setType(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setColor(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSmell(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDensity(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setVitality(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setMotilityRate(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setLine(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setOperator(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setResult(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Storage entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Storage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Storage entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
